server:
  port: 8082

spring:
  application:
    name: rocketmq-consumer

rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    pull-batch-size: 10
    
logging:
  level:
    com.sh.cursortest: debug 