server:
  port: 8081

spring:
  application:
    name: rocketmq-producer

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
    send-message-timeout: 3000
    
logging:
  level:
    com.sh.cursortest: debug 